import type { Product } from "../types/index";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Geometric Cube",
    price: 299,
    description: "Perfect orange cube with smooth edges",
    shape: "3d-shape",
    geometry: "box",
    color: "orange",
    size: [2, 2, 2],
  },
  {
    id: "2",
    name: "Crystal Sphere",
    price: 450,
    description: "Elegant blue sphere with perfect symmetry",
    shape: "3d-shape",
    geometry: "sphere",
    color: "#4FC3F7",
    size: [1.5, 1.5, 1.5],
  },
  {
    id: "3",
    name: "Modern Cylinder",
    price: 380,
    description: "Sleek green cylinder for contemporary spaces",
    shape: "3d-shape",
    geometry: "cylinder",
    color: "#81C784",
    size: [1, 3, 1],
  },
  {
    id: "4",
    name: "Pyramid Cone",
    price: 320,
    description: "Mystical purple cone with ancient vibes",
    shape: "3d-shape",
    geometry: "cone",
    color: "#BA68C8",
    size: [1.5, 2.5, 1.5],
  },
  {
    id: "5",
    name: "Cosmic Torus",
    price: 520,
    description: "Hypnotic pink torus from another dimension",
    shape: "3d-shape",
    geometry: "torus",
    color: "#F06292",
    size: [2, 2, 0.5],
  },
  {
    id: "6",
    name: "Diamond Octahedron",
    price: 680,
    description: "Luxurious golden octahedron with premium finish",
    shape: "3d-shape",
    geometry: "octahedron",
    color: "#FFD54F",
    size: [2, 2, 2],
  },
] as const;
